backend:
  name: git-gateway
  branch: main

media_folder: "gallery/images"
public_folder: "/gallery/images"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "gallery/items"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Image", widget: "image" }
